server:
  port: 8888
  servlet:
    #访问根路径
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    min-spare-threads: 500
    max-threads: 1000
    max-connections: 3500
    accept-count: 500
  max-http-header-size: 1048576
  undertow:
    max-http-post-size: 2097152
  netty:
    connection-timeout: 2000
spring:
  datasource:
    url: jdbc:mysql://localhost:4306/happy?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: happy
    password: Happy@2023
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # mysql端单用户最大连接数为?
      max-active: 180
      initial-size: 20
      min-idle: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能，默认是true
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能，默认是false
      test-on-return: false
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      # Destroy线程会检测连接的间隔时间(默认1分钟)，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1
      # 连接保持空闲而不被驱逐的最小时间，mysql端空闲连接最长时间为30分钟
      min-evictable-idle-time-millis: 300000
  jackson:
    # 对值为null的字段不序列化
    default-property-inclusion: non_null
    # json->obj时，如果obj没有json中的某个字段时，如果为false则不抛异常
    deserialization:
      fail_on_unknown_properties: false
    # 设置全局时区
    time-zone: GMT+8
    # 设置属性命名策略,对应jackson下PropertyNamingStrategy中的常量值，SNAKE_CASE-返回的json驼峰式转下划线，json body下划线传到后端自动转驼峰式
    property-naming-strategy: SNAKE_CASE
    # 当地时区
    locale: zh_CN
    # 全局设置@JsonFormat的格式pattern
    date-format: yyyy-MM-dd HH:mm:ss
    local-date-format: yyyy-MM-dd
    local-time-format: HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
mybatis-plus:
  # type-enums-package: com.gomepay.goa.www.api.auth.enums
  mapper-locations: classpath*:/com/happy/**/*Mapper.xml
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:log4j2-dev.xml